server:
  port: 8090

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: db-config.properties
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver-class-name}

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true