server:
  port: 8090

logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  config:
    import: db-config.properties
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver-class-name}

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
