server:
  port: 8090

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  secret: xDpfIyUPoKOjCnsv4AusxHx1kFGxUHw8hfhPGI6LNCe/0/aRE8UpflouCRT8tNLZIHinyGSHplafUejafUOABA==
  access-token-validity-in-seconds: 7200 # 2시간
  refresh-token-validity-in-seconds: 43200 # 12시간

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: db-config.properties
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver-class-name}
  mail:
    host: smtp.gmail.com  #{SMTP 서버 호스트}
    port: 587 #{SMTP 서버 포트}
    username: ${mail.username} #{SMTP 서버 로그인 아이디}
    password: ${mail.password} #{SMTP 서버 로그인 패스워드}
    properties:
      mail:
        smtp:
          auth: true #{사용자 인증 시도 여부 (기본값 : false)}
          timeout: 5000 #{Socket Read Timeout 시간 ms (기본값 : 무한대)}
          starttls:
            enable: true #{StartTLS 활성화 여부 (기본값 : false)}
  # redis
  redis:
    host: 34.29.123.82
    port: 6379
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true